name: 'Terragrunt Action'
description: 'Run Terragrunt commands in GitHub Actions'

inputs:
  command:
    description: 'Terragrunt command to execute (plan, apply, etc.)'
    required: true
    default: 'plan'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/usr/local/bin/entrypoint.sh'
