name: 'Terragrunt Action'
description: 'An action to run Terragrunt commands using a custom Docker image.'
inputs:
  command:
    description: 'The Terragrunt command to run (plan or apply)'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: python3 /usr/local/bin/entrypoint.py